### ISSUE TITLE
Licensing and reusing

### ISSUE THREAD

**Issue by szpak** [testcontainers/workshop#21]
Working on my Testcontainers presentation I wanted to create a sample/simple application with some use cases for the live coding section. However, in the meantime, I have found this workshop. I wonder what is the license of that project and can I use it and adapt to my needs (such as a variant in Spock or JUnit 5)?

Of course with the proper attribution where does this project come from.

**Comment by bsideup** [comment]
Hi @szpak! The file seems to be missing indeed. I created #22 to fix it, will merge as soon as other major contributors (@rnorth @kiview) approve it

**Comment by szpak** [comment]
Thanks!
