### ISSUE TITLE
Add notice in step 3 that port must be available

### ISSUE THREAD

**Issue by Bukama** [testcontainers/workshop#24]
I'm just going through the workshop and failed at step 3 "Our very first test"  running the dummy test `com.example.demo.DemoApplicationTest` because the build in tomcat webserver could not be estabilshed.

It turned out that I had to stop `Docker Desktop` which was running in parallel. So I think they used the same port (8000 or 8080 as these were used by Docker).

I think there should be a note in the description. It may sounds obvious if you are familiar with Spring (which I never had worked with), but as someone like me who started with the official docker tutorial may get struck.

edit:
Maybe add the environment requirements in the workshop - what software has to be installed (and maybe how)

**Comment by bsideup** [comment]
The application is self contained and uses random ports, so it doesn't look like it was caused by the app under the tests.
