### ISSUE TITLE
Workshop Missing details on configuring Kafka

### ISSUE THREAD

**Issue by cortizqgithub** [testcontainers/workshop#32]
Kafka config not clear

The only thing written is 

"Running Kafka in Docker is easy with TestContainers. There is a Testcontainers module providing integration with Kafka and the KafkaContainer abstraction for your code.

Just add it the same way as you added Redis and set the spring.kafka.bootstrap-servers system property.

I tried to do as instructed but the tests are failing.

```java
static final GenericContainer<?> kafka = new GenericContainer("confluentinc/cp-kafka:5.4.6").withExposedPorts(9092);
```

And in the DynamicPropertySource annotation I wrote

```java
@DynamicPropertySource
public static void configureRedisKafka(DynamicPropertyRegistry registry) {
    Stream.of(redis,kafka).parallel().forEach(GenericContainer::start);
    registry.add("spring.redis.host", redis::getHost);
    registry.add("spring.redis.port", redis::getFirstMappedPort);
    registry.add("spring.kafka.bostrap-servers", kafka::getHost);
}
```

Thus, what is the correct solution?

**Comment by cortizqgithub** [comment]
I am following the tutorial and I got stuck here. The purpose of the tutorial is to help oneself understand the concepts. Thanks!

**Comment by kiview** [comment]
The workshop follows a certain didactic concept, that requires learners to dig into the docs and the code itself to figure out solutions. It is in its current form not intended to be a 100% step-by-step guide that contains all solutions. Furthermore, it is run as an interactive workshop at conferences and other occasions by Testcontainers maintainers, so it is not a 100% self-learning tutorial.

Regarding your question, but without spoiling the solution, please have a look at the official documentation: https://www.testcontainers.org/modules/kafka/
